-- 2021-10-10 14:22:39

CREATE TABLE IF NOT EXISTS `paste` (
  `id` varchar(36) NOT NULL,
  `content` mediumtext NOT NULL,
  `created` timestamp NOT NULL,
  `hash` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hash` (`hash`)
);

INSERT INTO `paste` (`id`, `content`, `created`, `hash`) VALUES
('-1CKNgES7jorJ82ihHTT1',	'<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Decimal Clock</title>\n    <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n<body>\n    <h2>Decimal Clock</h2>\n    <div id=\"clock-face\"></div>\n    <h1 id=\"clock-time\"></h1>\n    <script src=\"script.js\"></script>\n</body>\n</html>',	'2021-10-10 14:21:14',	'e5a6487934f50bde446dab12e2ae96e527c106fd2fe65acde997001a'),
('9fQdz0jxUXDqs2IyhW2cd',	'package resources\n\nimport (\n	\"net/url\"\n	\"strings\"\n)\n\n// ParseURL converts given database connection string url into a DSN format.\nfunc ParseURL(connstr string) (out string, err error) {\n	// Validate it first\n	if strings.HasPrefix(connstr, \"mysql://\") {\n		// MySQL DSN format is: username:password@tcp(127.0.0.1:3306)/test\n		parsedConn, err := url.Parse(connstr)\n		if err != nil {\n			return out, err\n		}\n\n		out += parsedConn.User.String()\n		out += \"@\"\n		out += \"tcp(\"\n		out += parsedConn.Hostname()\n		out += \":\"\n		out += parsedConn.Port()\n		out += \")\"\n		out += parsedConn.EscapedPath()\n		out += \"?\"\n		out += parsedConn.Query().Encode()\n\n		return out, err\n	} else if strings.HasPrefix(connstr, \"postgres://\") || strings.HasPrefix(connstr, \"postgresql://\") {\n		// PostgreSQL DSN format is: user=bob password=secret host=1.2.3.4 port=5432 dbname=mydb sslmode=verify-full\n		parsedConn, err := url.Parse(connstr)\n		if err != nil {\n			return out, err\n		}\n\n		pwd, _ := parsedConn.User.Password()\n\n		out += \"user=\"\n		out += parsedConn.User.Username()\n		out += \" password=\"\n		out += pwd\n		out += \" host=\"\n		out += parsedConn.Hostname()\n		out += \" port=\"\n		out += parsedConn.Port()\n		out += \" dbname=\"\n		out += strings.Replace(parsedConn.EscapedPath(), \"/\", \"\", 1)\n		out += \" \"\n		out += strings.Join(strings.Split(parsedConn.Query().Encode(), \"&\"), \" \")\n\n		return out, err\n	}\n\n	return connstr, nil\n}\n',	'2021-10-10 14:21:43',	'127fc2633f3a2e589e8a8d54d278b3660318b36c86c2592a06f239cd'),
('bErUc4T6sXta05KUVhwwU',	'import options from \"commander\"\nimport fs from \"fs-extra\"\nimport * as env from \"./buildSrc/env.js\"\nimport {renderHtml} from \"./buildSrc/LaunchHtml.js\"\nimport {spawn, spawnSync} from \"child_process\"\nimport path, {dirname} from \"path\"\nimport {fetchDictionaries} from \'\'./buildSrc/DictionaryFetcher.js\'\'\nimport os from \"os\"\nimport {rollup} from \"rollup\"\nimport {babelPlugins, bundleDependencyCheckPlugin, getChunkName, resolveLibs} from \"./buildSrc/RollupConfig.js\"\nimport {terser} from \"rollup-plugin-terser\"\nimport pluginBabel from \"@rollup/plugin-babel\"\nimport commonjs from \"@rollup/plugin-commonjs\"\nimport {fileURLToPath} from \"url\"\nimport nodeResolve from \"@rollup/plugin-node-resolve\"\nimport {visualizer} from \"rollup-plugin-visualizer\"\nimport glob from \"glob\"',	'2021-10-10 14:20:58',	'31b7c305e1f55cc33d25b26f716fddddd220045e0314bb8bbc4e5007'),
('cd32QItTvQ1WzGXQAN0NC',	'{\n	\"chatID\": \"2318301\",\n	\"command\": \"test\",\n	\"message\": \"test!\"\n}',	'2021-10-10 14:20:50',	'3bfeb32b59a9ce982bb99f27eacc152ea07ff291e9ebffcbffae5141'),
('dj1WRH_n_sNXbC7sc7_NE',	'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure? On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee.',	'2021-10-10 14:20:31',	'82b8062337a0c5d64e07ad3e7cc5ed96f4d71bcbbf871ca97e0cd534');
