name: PR

on:
  pull_request:

jobs:
  scan:
    name: Secret scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified

  ci:
    name: CI / ${{ matrix.arch.arch }}
    runs-on: ${{ matrix.arch.runs-on }}
    timeout-minutes: 20
    container: golang:1.24
    strategy:
      fail-fast: true
      matrix:
        arch:
          - runs-on: ubuntu-24.04
            arch: amd64
          - runs-on: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: go build -buildvcs=false .

      - name: Run test & coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
        env:
          ENVIRONMENT: development
          PORT: 3000
          DATABASE_URL: mysql://root:password@db:3306/polarite
          REDIS_URL: redis://@cache:6379
          TZ: UTC

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - uses: codecov/codecov-action@v3
