name: Check

on:
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: golang:1.17.2
    services:
      db:
        image: mysql:8.0.26
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: polarite
          MYSQL_ROOT_PASSWORD: password
        cap_add:
          - SYS_NICE
      cache:
        image: redis:6.2.6-alpine
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installling dependencies
        run: go mod vendor

      - name: Build
        run: go build main.go app.go

      - name: Run test & coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
        env:
          ENVIRONMENT: development
          PORT: 3000
          DATABASE_URL: mysql://root:password@db:3306/polarite
          REDIS_URL: redis://@cache:6379
          TZ: UTC

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - uses: codecov/codecov-action@v2
